/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocialNetworkServer;

/**
 *
 * @author zakbo
 */
public class SocialNetworkServer extends javax.swing.JFrame {
    static boolean isServerOnline = false; //Is the server online
    /**
     * Creates new form SocialNetworkServer
     */
    public SocialNetworkServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_Text = new javax.swing.JLabel();
        launch_Button = new javax.swing.JButton();
        close_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_Text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title_Text.setText("Social Network Server Control");

        launch_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        launch_Button.setText("Launch Server");
        launch_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launch_ButtonActionPerformed(evt);
            }
        });

        close_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        close_Button.setText("Close Server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(title_Text)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(launch_Button)
                .addGap(18, 18, 18)
                .addComponent(close_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(launch_Button)
                    .addComponent(close_Button))
                .addGap(0, 285, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launch_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launch_ButtonActionPerformed
        isServerOnline = true;
        System.out.println("button");
    }//GEN-LAST:event_launch_ButtonActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocialNetworkServer().setVisible(true);
                serverCode serverRun = new serverCode();
                serverRun.run();
            }
        });
        
        
//        } try
//        {
//        //SNServer == Social Network Server
//        ServerSocket SNServer = new ServerSocket(9999);
//        Socket test = SNServer.accept();
//        
//        System.out.println("Connected!!!!!!!!!!");
//        }
//        catch(Exception e)
//        {
//            System.out.println("error");
//        }
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_Button;
    private javax.swing.JButton launch_Button;
    private javax.swing.JLabel title_Text;
    // End of variables declaration//GEN-END:variables
   
}

class serverCode implements Runnable{
    public serverCode(){
    
}
    public void run()
    {
        if(SocialNetworkServer.isServerOnline == true)
        {
            System.out.println("qwerty");
        }
    }
        
}